tools/eval.py
keep pretrained=Fasle when eval
fix issue #130
=> keep pretrained=Fasle when eval, fix issue #130

tests/ut/test_models.py
=> fix test model by name

mindocr/__init__.py, mindocr/data/__init__.py, mindocr/data/builder.py, mindocr/data/transforms/__init__.py, mindocr/losses/__init__.py, mindocr/losses/builder.py, mindocr/metrics/__init__.py, mindocr/metrics/builder.py, mindocr/models/__init__.py, mindocr/models/backbones/__init__.py, mindocr/models/builder.py, mindocr/models/heads/__init__.py, mindocr/models/necks/__init__.py, mindocr/postprocess/__init__.py, mindocr/postprocess/builder.py, mindocr/utils/__init__.py, mindocr/utils/visualize.py, mindocr/version.py, tests/ut/test_models.py
=> improve init

deploy/mx_infer/processors/common/collect_process.py, docs/cn/inference_cn.md
1. fix bug for saving when results is empty.
2. fix a error name for download link
=> fix bug for inference

mindocr/postprocess/det_postprocess.py
cv2版本不同，导致cv2.findContours返回值个数不同。
=> fix cv2.findContours version bug

configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md
=> update crnn readme

mindocr/models/det_dbnet.py
=> fix dbnet ckpt url

mindocr/models/backbones/mindcv_models/utils.py, mindocr/models/det_dbnet.py, mindocr/models/rec_crnn.py, tests/ut/test_models.py
=> fix predefined model download

__init__.py, mindocr/data/transforms/general_transforms.py, mindocr/utils/callbacks.py, mindocr/utils/visualize.py
=> fix setup import

.github/workflows/ci.yml, tests/st/test_train_eval_dummy.py, tests/ut/_common.py, tests/ut/test_datasets.py, tests/ut/test_loss.py, tests/ut/test_metrics.py, tests/ut/test_models.py, tests/ut/test_postprocess.py
=> rm redundant packages and add ut to workflow

README.md, README_CN.md
=> fix readme url bug

.github/workflows/ci.yml, README.md, README_CN.md
update mainpage readme
update link in mainpage readme
state the required mindspore and python version
Issue #99
=> update mainpage readme

mindocr/optim/adamw.py, mindocr/optim/adan.py, mindocr/optim/lion.py, mindocr/optim/nadam.py
Use python assert instead of mindspore._checkparam
=> rm _checkparam usage

mindocr/data/builder.py, tools/eval.py
=> fix evaluation error due to non-divisable batch_size

README.md, configs/rec/crnn/crnn_icdar15.yaml, mindocr/optim/__init__.py, mindocr/optim/optim_factory.py, mindocr/optim/param_grouping.py, tests/ut/test_group_params.py, tools/train.py
=> Add group params support

deploy/mx_infer/framework/__init__.py, deploy/mx_infer/framework/infer_engine/__init__.py, deploy/mx_infer/framework/infer_engine/lite.py, deploy/mx_infer/framework/infer_engine/mindx.py, deploy/mx_infer/framework/infer_engine/model_base.py, deploy/mx_infer/framework/module_base.py, deploy/mx_infer/framework/module_data_type.py, deploy/mx_infer/framework/module_infer.py, deploy/mx_infer/framework/module_manager.py, deploy/mx_infer/pipeline_args.py, deploy/mx_infer/processors/classification/cls_infer_process.py, deploy/mx_infer/processors/classification/cls_pre_process.py, deploy/mx_infer/processors/common/collect_process.py, deploy/mx_infer/processors/common/decode_process.py, deploy/mx_infer/processors/detection/det_infer_process.py, deploy/mx_infer/processors/recognition/rec_infer_process.py, deploy/mx_infer/processors/recognition/rec_pre_process.py, deploy/mx_infer/utils/__init__.py, deploy/mx_infer/utils/cv_utils.py, deploy/mx_infer/utils/safe_utils.py
add mslite support for inference.
=> add mslite support for inference

mindocr/optim/optim_factory.py
Duplicated `if weight_decay and filter_bias_and_bn` condition.
=> warning bug fix

mindocr/models/backbones/mindcv_models/download.py, requirements.txt
=> solve download fail bugs in some servers

requirements.txt
https://github.com/mindspore-lab/mindocr/issues/195
=> fix requirements on imgaug

docs/cn/datasets/mlt2017_CN.md, docs/en/datasets/mlt2017.md, tools/dataset_converters/convert.py, tools/dataset_converters/mlt2017.py
Add support for MLT2017 dataset.
=> modify MLT2017_Converter to support official dataset labels

mindocr/models/necks/select.py
When the backbone output feature is not a list but a feature Tensor, Select may not work correctly.
(How should this PR be tested? Do you require a special setup to run the test or repro the fixed bug?)
=> improve select layer

mindocr/data/rec_lmdb_dataset.py
=> better error msg for empty lmdb dataset

mindocr/metrics/det_metrics.py
… distributed evaluation error
=> revert det_metric to commit cec71024186 because commit 837ff68 incurs bug in distributed evaluation

configs/rec/crnn/crnn_icdar15.yaml, mindocr/utils/callbacks.py, mindocr/utils/ema.py, mindocr/utils/train_step_wrapper.py, tests/st/test_train_eval_dummy.py, tests/ut/_common.py, tools/train.py
EMA is a typical trick to improve training performance especially for stable loss convergence.
=> add ema and improve log

configs/det/dbnet/db_r18_icdar15.yaml, configs/det/dbnet/db_r50_icdar15.yaml, configs/det/dbnet/db_r50_synthtext.yaml, mindocr/data/transforms/det_transforms.py, mindocr/data/transforms/general_transforms.py, mindocr/data/transforms/iaa_augment.py
Added probabilities to augmentations to avoid introducing bias for some datasets.
Improved polygon validation and clipping process (instead of simply clipping with `np.clip`).
=> improve detection augmentation pipeline

mindocr/data/det_dataset.py
fixed dataset null annotation bug
=> fixed dataset null annotation bug

mindocr/data/det_dataset.py
=> fix `list index out of range` error for detection dataset

tools/arg_parser.py, tools/train.py
=> Support downloading multi data in modelart

configs/rec/crnn/crnn_icdar15.yaml, configs/rec/crnn/crnn_resnet34.yaml, configs/rec/crnn/crnn_vgg7.yaml, mindocr/utils/model_wrapper.py, tools/train.py
=> fix amp for crnn with CTCLoss

mindocr/utils/callbacks.py, mindocr/utils/misc.py
=> Add loss average meter

configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/rare/README.md, configs/rec/rare/README_CN.md
=> improve docs for chinese text dataset training

mindocr/models/necks/select.py
Inherit nn.Cell, otherwise neck `Select` cannot run in graph mode.
=> fix neck `Select` bug in graph mode

mindocr/data/transforms/rec_transforms.py, mindocr/data/transforms/transforms_factory.py
=> fix the transform bug and raise the exception when return is null

.github/workflows/ci.yml
=> Add cpplint check to ci.yml

mindocr/models/utils/load_model.py
=> fix the local checkpoint loading

tools/arg_parser.py, tools/train.py
=> Fix modelart after new CLI change and remove redudant import

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/dbnet/db_r18_ctw1500.yaml, configs/det/dbnet/db_r18_mlt2017.yaml, configs/det/dbnet/db_r18_synthtext.yaml, configs/det/dbnet/db_r18_td500.yaml, configs/det/dbnet/db_r18_totaltext.yaml, configs/det/dbnet/db_r50_ctw1500.yaml, configs/det/dbnet/db_r50_mlt2017.yaml, configs/det/dbnet/db_r50_totaltext.yaml
add dbnet yaml for synthtext, mlt2017, td500, totaltext and ctw1500 dataset
related issues #222 
=> add dbnet yaml for synthtext, mlt2017, td500, totaltext and ctw1500 dataset

configs/det/east/README_CN.md, configs/det/east/east_r50_icdar15.yaml, deploy/py_infer/src/data_process/postprocess/det_postprocess.py, deploy/py_infer/src/data_process/postprocess/postprocess_mapping.py, deploy/py_infer/src/utils/adapted/mindocr_models.py, mindocr/data/transforms/det_east_transforms.py, mindocr/data/transforms/transforms_factory.py, mindocr/losses/builder.py, mindocr/losses/det_loss.py, mindocr/models/__init__.py, mindocr/models/det_east.py, mindocr/models/heads/builder.py, mindocr/models/heads/det_east_head.py, mindocr/models/necks/builder.py, mindocr/models/necks/fpn.py, mindocr/postprocess/builder.py, mindocr/postprocess/det_db_postprocess.py, mindocr/postprocess/det_east_postprocess.py, requirements.txt
add east det model, where the best f-score is 84.95%, compared with modelzoo +3.99%, compared with paddleocr +0.05%.
=> add east det model

configs/det/psenet/README.md, configs/det/psenet/README_CN.md, deploy/py_infer/src/data_process/postprocess/det_postprocess.py, deploy/py_infer/src/data_process/postprocess/postprocess_mapping.py, deploy/py_infer/src/utils/adapted/mindocr_models.py, docs/cn/inference/environment_cn.md, docs/en/inference/environment_en.md, mindocr/postprocess/det_pse_postprocess.py, mindocr/postprocess/pse/__init__.py
support PSENet MindIR inference and add inference tutorial in readme, fix some typo in documents.
=> support PSENet MindIR inference

deploy/py_infer/src/data_process/postprocess/postprocess_mapping.py
=> fix EAST MindIR inference postprocess

README.md, README_CN.md, configs/det/east/README.md, configs/det/east/README_CN.md
=> update main readme for supporting EAST model; improve readme_cn of EAST; add readme_en of EAST

configs/README.md, mindocr/metrics/rec_metrics.py, tools/export.py
=> fix metric bugs for lower, support mindir export with model yaml config

mindocr/utils/callbacks.py, mindocr/utils/checkpoint.py, mindocr/utils/recorder.py, tools/train.py
When training is interrupted, the resume training function can be used to continue training from the interrupted point.
For use this function, you can set the parameter cfg.model.resume is True or path to resume checkpoint.
#77 
=> add resume training

configs/det/psenet/README.md, configs/det/psenet/README_CN.md
更新PSENet的推理Readme
提供个样例，其它模型的Readme都按照这种格式来更新。
=> fix readme for psenet inference

mindocr/postprocess/det_base_postprocess.py
=> fix DetBasePostprocess bug

.flake8, .github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.md
=> Add pre-commit and lint

.github/workflows/ci.yml
remove pre-commit check in CI and will fix pre-commit later
=> remove pre-commit check in CI

configs/det/east/README.md, configs/det/east/README_CN.md
=> update readme of EAST for MindSpore Lite inference guideline

deploy/py_infer/src/data_process/postprocess/det_east_postprocess.py
=> fix east for inference

deploy/py_infer/src/configs/rec/ppocr/ch_PP-OCRv2_rec_distillation.yaml, deploy/py_infer/src/configs/rec/ppocr/ch_PP-OCRv3_rec_distillation.yml, deploy/py_infer/src/configs/rec/ppocr/en_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/rec_en_number_lite_train.yaml, deploy/py_infer/src/data_process/utils/gear_utils.py
Improve gear strategy and fix yaml config for pp-ocr inference
Already tested on pp-ocr models
=> Improve gear strategy and fix yaml config for pp-ocr inference

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md
=> add dbnet inference readme

mindocr/data/transforms/det_east_transforms.py, mindocr/losses/det_loss.py, mindocr/models/heads/det_east_head.py
=> adapt EAST to ms2.0

mindocr/data/rec_lmdb_dataset.py, tools/benchmarking/multi_dataset_eval.py, tools/eval.py, tools/train.py
=> TMP Fix for ms1.7 

docs/cn/tutorials/distribute_train_CN.md
=> add distribute tutorials

.flake8, deploy/eval_utils/eval_det.py, deploy/eval_utils/eval_rec.py, deploy/py_infer/infer.py, deploy/py_infer/src/data_process/postprocess/det_east_postprocess.py, deploy/py_infer/src/data_process/postprocess/det_postprocess.py, deploy/py_infer/src/data_process/postprocess/rec_postprocess.py, deploy/py_infer/src/data_process/preprocess/preprocess_mapping.py, deploy/py_infer/src/data_process/preprocess/transforms/det_transforms.py, deploy/py_infer/src/data_process/preprocess/transforms/general_transforms.py, deploy/py_infer/src/data_process/preprocess/transforms/rec_transforms.py
1.修复一些代码格式问题，不再屏蔽
2.补上svtr的预处理SVTRRecResizeImg
3. 另外由于不支持动态shape，如果SVTRRecResizeImg传入padding=False，则给出WARNNING
=> clean code and fix dynamic shape for svtr

configs/cls/mobilenetv3/README.md, configs/cls/mobilenetv3/README_CN.md, configs/cls/mobilenetv3/cls_mv3.yaml, mindocr/data/transforms/rec_transforms.py, mindocr/losses/builder.py, mindocr/losses/cls_loss.py, mindocr/metrics/builder.py, mindocr/metrics/cls_metrics.py, mindocr/models/README.md, mindocr/models/__init__.py, mindocr/models/backbones/__init__.py, mindocr/models/backbones/cls_mobilenet_v3.py, mindocr/models/backbones/mindcv_models/mobilenet_v3.py, mindocr/models/cls_mv3.py, mindocr/models/heads/builder.py, mindocr/models/heads/cls_mv3_head.py, mindocr/postprocess/builder.py, mindocr/postprocess/cls_postprocess.py, tests/ut/test_models.py, tools/eval.py, tools/train.py
- add mobilenetv3_small_100 as text direction classification model.
- achieve evaluation accuracy 94.59%, higher than paddleocr 94.56%.
- docs will be updated later.
=> add text direction classification model (mobilenetv3_small_100)

configs/det/psenet/README.md, configs/det/psenet/README_CN.md, configs/det/psenet/pse_r152_ctw1500.yaml
Add PSENet model trained on CTW1500
=> Add Chinese PSENet model trained on CTW1500

docs/cn/datasets/chinese_text_recognition_CN.md, docs/cn/datasets/ctw1500_CN.md, docs/cn/datasets/svt_CN.md, docs/cn/datasets/td500_CN.md, docs/en/datasets/chinese_text_recognition.md, docs/en/datasets/ctw1500.md, docs/en/datasets/svt.md, docs/en/datasets/td500.md, tools/dataset_converters/README.md, tools/dataset_converters/README_CN.md
- Update link to more dataset docs in tools/data_converters/README.md
- Add 'Back to README' button to make the docs more user friendly
=> update data_converter doc

deploy/py_infer/src/configs/det/mmocr/dbnetpp_resnet50_fpnc_1200e_icdar2015.yaml, deploy/py_infer/src/configs/det/mmocr/fcenet_resnet50_fpn_1500e_icdar2015.yaml, deploy/py_infer/src/data_process/postprocess/det_fce_postprocess.py, deploy/py_infer/src/data_process/postprocess/det_postprocess.py, deploy/py_infer/src/data_process/postprocess/postprocess_mapping.py, deploy/py_infer/src/data_process/preprocess/preprocess_mapping.py, deploy/py_infer/src/data_process/preprocess/transforms/det_transforms.py, deploy/py_infer/src/data_process/utils/mask_utils.py, deploy/py_infer/src/data_process/utils/polygon_utils.py, deploy/py_infer/src/utils/adapted/__init__.py, deploy/py_infer/src/utils/adapted/mmocr_models.py, docs/cn/inference/convert_tutorial_cn.md, docs/cn/inference/model_perf_thirdparty_cn.md, docs/cn/inference/models_list_thirdparty_cn.md, docs/en/inference/convert_tutorial_en.md, docs/en/inference/model_perf_thirdparty_en.md, docs/en/inference/models_list_thirdparty_en.md
=> Add mmocr dbnet++ and fcenet

deploy/py_infer/src/configs/rec/ppocr/arabic_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/chinese_cht_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/cyrillic_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/devanagari_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/japan_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/ka_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/korean_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/latin_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/ta_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/te_PP-OCRv3_rec.yaml
Change the RecResizeImg transform in pp-ocr inference yaml to RecResizeNormForInter
=> Change RecResizeImg to RecResizeNormForInfer

configs/cls/mobilenetv3/cls_mv3.yaml, mindocr/postprocess/cls_postprocess.py
To align with other postprocess class name, modify class name `ClsPostProcess` to `ClsPostprocess`
=> modify clspostprocess name

deploy/py_infer/src/data_process/preprocess/preprocess_mapping.py, deploy/py_infer/src/data_process/preprocess/transforms/rec_transforms.py, tests/ut/test_infer_datasets.py
=> delete RecResizeImg from infer

mindocr/postprocess/rec_postprocess.py
=> fix the rare postprocess error when lower is true or the image is exactly <STOP>

docs/cn/inference/inference_tutorial_cn.md, docs/en/inference/inference_tutorial_en.md
1. 用markdown格式化工具格式化readme文件
2. 对齐缩进空格
=> format inference_tutorial

configs/rec/rare/README.md, docs/cn/datasets/chinese_text_recognition_CN.md, docs/en/datasets/chinese_text_recognition.md
=> Fix typo and update link

docs/cn/inference/model_perf_thirdparty_cn.md, docs/en/inference/model_perf_thirdparty_en.md
Add ppocr PSENet inference performance
=> Add ppocr PSENet performance

mindocr/postprocess/det_east_postprocess.py
=> improve EAST postprocess if detection result is empty

README.md, docs/cn/tutorials/training_on_openi.md, docs/en/tutorials/advanced_train.md
=> Re-organize readme, add two tutorials

docs/cn/tutorials/training_recognition_custom_dataset.md, docs/en/tutorials/training_recognition_custom_dataset.md
=> Update Recognition Training Doc

README_CN.md
=> update readme cn

README_CN.md
=> [fix] Update README_CN.md

deploy/eval_utils/eval_rec.py
=> [fix] bug fix

mindocr/data/transforms/det_transforms.py, mindocr/data/transforms/general_transforms.py, mindocr/losses/det_loss.py, mindocr/metrics/det_metrics.py, mindocr/models/backbones/det_mobilenet.py, mindocr/models/backbones/det_resnet.py, mindocr/models/heads/det_db_head.py, mindocr/models/necks/asf.py, mindocr/models/necks/fpn.py, mindocr/postprocess/det_base_postprocess.py, mindocr/postprocess/det_db_postprocess.py, mindocr/postprocess/det_east_postprocess.py, mindocr/postprocess/det_pse_postprocess.py
=> Add DBNet and DBNet++ API docs

docs/cn/inference/model_perf_thirdparty.md, docs/en/inference/model_perf_thirdparty.md
=> update infer readme

.gitignore
Model compiling on ascend produces thousands of files, this make git track happy
=> add MindSpore compile related to git ignore list

deploy/models_utils/onnx_optim/insert_pse_postprocess.py
Further improve ppocr psenet inference speed
=> ppocr psenet modify script update

tools/infer/text/utils.py
Allow to run inference on images located in multiple subdirectories.
=> allow to run inference on images located in multiple subdirectories

configs/det/psenet/pse_r152_icdar15.yaml, mindocr/data/transforms/det_transforms.py
Update psenet model config yaml to adapt to the new dataset pipeline.
Already tested on ms2.0 and witnessed 2~3 times speed improvement.
=> New dataset pipeline for PSENet upload

docs/cn/tutorials/yaml_configuration.md, mindocr/utils/callbacks.py
Using jit in callback leads to error in AICC environments. Considering it doesn't influence the performance due to the small computation of reduce sum, it deserves to be removed.
=> fix bugs in aicc and docs

docs/cn/tutorials/distribute_train.md, docs/en/tutorials/distribute_train.md
I read the distributed training tutorial and found it didn't explain all details I need to set the rank table on Ascend. I revised the tutorial and please make comments to make it easy to follow.
=> update distributed training docs

deploy/py_infer/src/infer/infer_det.py
=> Fix infer det bug for PSENet ic15

docs/en/inference/inference_tutorial.md
=> [fix] fix style error

mindocr/utils/callbacks.py
=> fix logger in callback

configs/det/fcenet/README_CN.md
=> update fcenet readme

mindocr/losses/det_loss.py
main branch CI fails due to linting problem in #466
=> linting fix

docs/cn/datasets/borndigital.md, docs/cn/datasets/casia10k.md, docs/cn/datasets/ccpd.md, docs/cn/datasets/cocotext.md, docs/cn/datasets/ctw.md, docs/cn/datasets/ic19_art.md, docs/cn/datasets/icdar2015.md, docs/cn/datasets/lsvt.md, docs/cn/datasets/mlt2017.md, docs/cn/datasets/mtwi2018.md, docs/cn/datasets/rctw17.md, docs/cn/datasets/rects.md, docs/cn/datasets/sroie.md, docs/cn/datasets/textocr.md, docs/cn/datasets/totaltext.md, docs/en/datasets/borndigital.md, docs/en/datasets/casia10k.md, docs/en/datasets/ccpd.md, docs/en/datasets/cocotext.md, docs/en/datasets/ctw.md, docs/en/datasets/ic19_art.md, docs/en/datasets/icdar2015.md, docs/en/datasets/lsvt.md, docs/en/datasets/mlt2017.md, docs/en/datasets/mtwi2018.md, docs/en/datasets/rctw17.md, docs/en/datasets/rects.md, docs/en/datasets/sroie.md, docs/en/datasets/textocr.md, docs/en/datasets/totaltext.md
=> fix datasets docs

README.md, README_CN.md, configs/rec/visionlan/README.md, configs/rec/visionlan/README_CN.md, configs/rec/visionlan/visionlan_resnet45_LA.yaml, configs/rec/visionlan/visionlan_resnet45_LF_1.yaml, configs/rec/visionlan/visionlan_resnet45_LF_2.yaml, docs/cn/index.md, docs/cn/mkdocs/modelzoo_training.md, docs/en/index.md, docs/en/mkdocs/modelzoo_training.md, mindocr/data/transforms/rec_transforms.py, mindocr/data/transforms/svtr_transform.py, mindocr/losses/builder.py, mindocr/losses/rec_loss.py, mindocr/models/__init__.py, mindocr/models/backbones/__init__.py, mindocr/models/backbones/rec_resnet45.py, mindocr/models/heads/builder.py, mindocr/models/heads/rec_visionlan_head.py, mindocr/models/rec_visionlan.py, mindocr/optim/param_grouping.py, mindocr/postprocess/rec_postprocess.py, mindocr/scheduler/scheduler_factory.py, tools/benchmarking/multi_dataset_eval.py
Visionlan training (on Ascend, amp_level=O2), evaluation, and readme, docs.
=> visionlan gpu updates

.github/workflows/python-publish.yml, mindocr/version.py
- update version to 0.2.0
- add pypi publish
=> update version to 0.2.0

mindocr/data/transforms/rec_transforms.py, mindocr/postprocess/rec_postprocess.py
=> improve RobustScanner preprocess & postprocess for inference

configs/rec/robustscanner/README.md, configs/rec/robustscanner/README_CN.md, configs/rec/robustscanner/robustscanner_resnet31.yaml, docs/cn/mkdocs/modelzoo_training.md, docs/en/mkdocs/modelzoo_training.md, mindocr/models/rec_robustscanner.py
=> update RobustScanner readme & models for improving accuracy

mindocr/models/builder.py, tools/benchmarking/multi_dataset_eval.py, tools/eval.py, tools/train.py
=> print the model parameters when train/eval the model

configs/det/fcenet/fce_icdar15.yaml, mindocr/losses/det_loss.py
This PR fixes issues that prevented FCENet from running in the `GRAPH` mode.
=> allow FCENet to run in GRAPH mode

configs/det/psenet/README.md, configs/det/psenet/README_CN.md, configs/det/psenet/pse_r50_icdar15.yaml, deploy/py_infer/src/utils/adapted/mindocr_models.py, docs/cn/mkdocs/modelzoo_training.md, docs/en/mkdocs/modelzoo_training.md, mindocr/models/det_psenet.py
Add ResNet50 support for PSENet
=> Add ResNet50 support for PSENet

configs/det/east/README.md, configs/det/east/README_CN.md, configs/det/east/east_mobilenetv3_icdar15.yaml, deploy/py_infer/src/utils/adapted/mindocr_models.py, docs/cn/mkdocs/modelzoo_training.md, docs/en/mkdocs/modelzoo_training.md, mindocr/models/det_east.py
=> add EAST with MobileNetV3 backbone

deploy/py_infer/src/utils/adapted/mindocr_models.py
=> PSENet ctw1500 inference support

mindocr/losses/det_loss.py
=> update Fce loss ops.matmul with float16

README.md, README_CN.md, docs/cn/inference/models_list.md, docs/cn/inference/models_list_thirdparty.md, docs/en/inference/models_list.md, docs/en/inference/models_list_thirdparty.md
=> Add inference tutorials for third-party models

deploy/py_infer/src/utils/visual_utils.py, docs/cn/inference/inference_tutorial.md, docs/en/inference/inference_tutorial.md
推理结果可视化部分，绘图时转为了RGB顺序，但是cv2.imwrite为BGR顺序，导致可视化结果的有问题
=> fix visualization bug for infer

.gitignore, README.md, README_CN.md, configs/README.md, docs/cn/inference/convert_tutorial.md, docs/cn/inference/inference_tutorial.md, docs/en/datasets/converters.md, docs/en/inference/convert_tutorial.md, docs/en/inference/inference_tutorial.md
Sort out the logic of the readme.
=> fix some readme

mindocr/models/necks/fpn.py
Adopt Rustam's suggestion from #479 
=> Move ResizeBilinearV2 into __init__

mindocr/models/base_model.py, mindocr/models/heads/rec_attn_head.py, mindocr/models/heads/rec_master_decoder.py
RARE / MASTER raises error ("model does not support tuple input") after the recent change. This is a fix.
=> Fix training when model head has multi input (e.g. RARE, MASTER)

tests/ut/_common.py
=> consistent batch size

configs/rec/visionlan/README.md, configs/rec/visionlan/README_CN.md, docs/cn/mkdocs/modelzoo_training.md, docs/en/mkdocs/modelzoo_training.md
Correct some minor errors in visionlan documents
=> visionlan docs updates

configs/rec/visionlan/README.md, configs/rec/visionlan/README_CN.md
minor changes on visionlan readme files.
=> visionlan readme updates

mindocr/data/transforms/det_fce_transforms.py
=> fixed  nonstrandard names in the pipeline data dictionary

configs/cls/mobilenetv3/README.md, configs/cls/mobilenetv3/README_CN.md, configs/cls/mobilenetv3/cls_mv3.yaml, mindocr/models/cls_mv3.py, mindocr/models/heads/builder.py, mindocr/models/heads/cls_head.py
=> rename ClsHead to MobileNetV3Head

configs/rec/master/README.md, configs/rec/master/README_CN.md, configs/rec/master/master_resnet31.yaml, mindocr/data/transforms/rec_transforms.py
=> data pipeline for master

tests/ut/test_mindir_export.py, tools/export.py
=> Support exporting mindir with dynamic input data shape

docs/cn/index_readme.md, docs/en/index_readme.md
=> fix mkdocs ci failure

docs/cn/datasets/ccpd.md, docs/en/datasets/ccpd.md, tools/dataset_converters/ccpd.py, tools/dataset_converters/convert.py
CCPD-Green is an expansion of CCPD2019 for electric vehicles.
=> add CCPD-Green 

tools/arg_parser.py, tools/train.py
=> openi support pretrained model

mindocr/models/backbones/layoutxlm/layoutxlm.py
=> add layoutxlm modules

configs/det/dbnet/db_r50_icdar15.yaml
This is an addition to PR #269 where the config file was not fully updated. This PR updates the config to ensure result reproducibility.
=> DBNet ICDAR2015 config fix

mindocr/models/backbones/layout_xlm_ms/conversion_utils.py, mindocr/models/backbones/layout_xlm_ms/visual_backbone.py
=> Add conversion script and fix bugs of visual backbone

mindocr/models/backbones/layout_xlm_ms/conversion_utils.py
=> Fix conversion utils bug

mindocr/models/backbones/layoutxlm/downloader.py, mindocr/models/backbones/layoutxlm/tokenizer.py, mindocr/models/backbones/layoutxlm/tokenizer_utils.py, mindocr/models/backbones/layoutxlm/tokenizer_utils_base.py, mindocr/models/backbones/layoutxlm/utils.py, mindocr/models/backbones/layoutxlm/vocab.py
=> add layoutxlm tokenizer

mindocr/models/backbones/layout_xlm_ms/layoutxlm.py, mindocr/models/backbones/layout_xlm_ms/test_utils.py
1. Add TokenClassification and LayoutXLMForSer (only TokenClassifcation verified)
2. Update tests for LayoutXLM model
=> Add TokenClassification and update tests

mindocr/data/transforms/layoutlm_transforms.py, mindocr/data/transforms/transforms_factory.py, mindocr/losses/layout_loss.py, mindocr/metrics/layout_metrics.py, mindocr/postprocess/builder.py, mindocr/postprocess/layout_token_re_postprocess.py, mindocr/postprocess/layout_token_ser_postprocess.py, mindocr/utils/utility.py
=> Add transformations, postprocess, metrics, loss for LayoutXLM Model

configs/det/fcenet/README.md, configs/det/fcenet/README_CN.md, configs/det/fcenet/fce_icdar15.yaml, mindocr/models/__init__.py, mindocr/models/det_fcenet.py, mindocr/models/heads/det_fce_head.py, mindocr/models/necks/fpn.py
=> fixed FCENet mindir export process

mindocr/models/backbones/layout_xlm_ms/__init__.py, mindocr/models/backbones/layout_xlm_ms/layoutxlm.py
Add LayoutXLMForSer and LayoutXLMForRe backbone
=> Add LayoutXLMForSer and LayoutXLMForRe backbone

mindocr/models/base_model.py
LayoutXLM-series models only have backbones.
=> Update base model to adapt for layoutXLM models

configs/kie/ser_layoutlm_xfund_zh.yaml, mindocr/data/builder.py, mindocr/data/layout_dataset.py, mindocr/models/backbones/layout_xlm_ms/visual_backbone.py
1. Upload training yaml for layoutxlm ser task;
2. Replace DotDict with addict Dict;
3. Add layoutxlm dataset definition.
=> Add layoutxlm dataset and training yaml

configs/kie/ser_layoutlm_xfund_zh.yaml, mindocr/data/transforms/layoutlm_transforms.py, mindocr/losses/builder.py, mindocr/losses/layout_loss.py, mindocr/metrics/builder.py, mindocr/metrics/layout_metrics.py, mindocr/models/backbones/layout_xlm_ms/layoutxlm.py, mindocr/models/backbones/layout_xlm_ms/visual_backbone.py, mindocr/models/base_model.py, mindocr/postprocess/builder.py, mindocr/postprocess/layout_token_re_postprocess.py, mindocr/postprocess/layout_token_ser_postprocess.py
=> Fix bugs for LayoutXLMSer model training

docs/cn/datasets/ccpd.md, docs/en/datasets/ccpd.md
Fixes issue: https://gitee.com/mindspore-lab/mindocr/issues/I7RZSB
https://gitee.com/mindspore-lab/mindocr/issues/I7RZSB
=> fix ccpd converter doc

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/east/README.md, configs/det/east/README_CN.md, configs/det/fcenet/README.md, configs/det/fcenet/README_CN.md, configs/det/psenet/README.md, configs/det/psenet/README_CN.md, configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/master/README.md, configs/rec/master/README_CN.md, configs/rec/rare/README.md, configs/rec/rare/README_CN.md, configs/rec/svtr/README.md, configs/rec/svtr/README_CN.md, configs/rec/visionlan/README.md, configs/rec/visionlan/README_CN.md, docs/cn/inference/convert_tutorial.md, docs/cn/inference/inference_quickstart.md, docs/cn/tutorials/training_detection_custom_dataset.md, docs/en/inference/convert_tutorial.md, docs/en/inference/inference_quickstart.md, docs/en/tutorials/training_detection_custom_dataset.md, tools/export.py
=> small fix on export.py

mindocr/models/backbones/mindcv_models/coat.py, mindocr/optim/adamw.py, mindocr/optim/adan.py, mindocr/optim/lion.py, mindocr/optim/nadam.py, mindocr/utils/ema.py, mindocr/utils/train_step_wrapper.py
optimize performance for PyNative mode.
=> optimize performance for pynative

deploy/py_infer/src/configs/rec/ppocr/arabic_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/chinese_cht_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/cyrillic_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/devanagari_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/en_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/japan_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/ka_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/korean_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/latin_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/rec_en_number_lite_train.yaml, deploy/py_infer/src/configs/rec/ppocr/ta_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/te_PP-OCRv3_rec.yaml
之前修改了后处理的加载顺序，优先加载mindocr自研模型的后处理代码
这几个模型的后处理与自研模型冲突，故打上from_ppocr标记，从而优先加载各自的后处理代码
=> fix postprocess conflict of third-party models

configs/rec/master/master_resnet31.yaml
=> fix Master inference performance

deploy/py_infer/src/utils/visual_utils.py, docs/cn/datasets/ccpd.md, docs/en/datasets/ccpd.md, mindocr/optim/adamw.py, mindocr/optim/adan.py, mindocr/optim/lion.py, mindocr/optim/nadam.py, tools/dataset_converters/ccpd.py
1. fix issue [#I8B8SV](https://e.gitee.com/mind_spore/projects/67813/tasks/list?issue=I8B8SV) which was caused by API changes of MindSpore r2.2.0
2. fix issue [#I7RZSB](https://gitee.com/mindspore-lab/mindocr/issues/I7RZSB) by correcting document bugs
3. fix bugs of exporting visual results when the text direction is vertical
=> fix issue #I8B8SV, #I7RZSB, and bug of exporting visual results

mindocr/data/transforms/svtr_transform.py
=> fix error from nested compose in SVTR Transform in MS2.2

configs/det/dbnet/README_CN_PP-OCRv3.md, configs/det/dbnet/db_mobilenetv3_ppocrv3.yaml, configs/rec/svtr/svtr_ppocrv3_ch.yaml
=> fix some details of PP-OCRv3 models yaml & readme

mindocr/models/backbones/layoutxlm/tokenizer.py
=> Fix tokenizer pretrained model url

configs/rec/svtr/README_CN_PP-OCRv3.md
=> update PP-OCRv3 README of online det & rec infer pipeline

deploy/py_infer/src/configs/cls/ppocr/cls_mv3.yaml, deploy/py_infer/src/configs/rec/ppocr/ch_PP-OCRv4_rec_distillation.yaml, deploy/py_infer/src/data_process/preprocess/transforms/rec_transforms.py, deploy/py_infer/src/utils/adapted/paddleocr_models.py, mindocr/data/transforms/rec_transforms.py
=> ppocrv4 cls + rec

configs/kie/layoutlm_series/ser_layoutxlm_xfund_zh.yaml, configs/kie/vi_layoutxlm/README_CN.md, configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yaml, mindocr/losses/kie_loss.py, mindocr/models/backbones/layoutxlm/layoutxlm.py, mindocr/models/backbones/layoutxlm/resnet.py
2.align visual backbone and its fine-tuning strategy 3.change the default value of batch_size and use_visual_backbone
=> 1.improve training speed of LayoutXLM and VI-LayoutXLM

README.md, README_CN.md, configs/layout/yolov8/README.md, configs/layout/yolov8/README_CN.md, configs/layout/yolov8/yolov8n.yaml
=> fix readme yolov8

mindocr/losses/kie_loss.py
=> Fix bugs of kie loss

README.md, README_CN.md, configs/table/README.md, configs/table/README_CN.md, configs/table/table_master.yaml, mindocr/data/builder.py, mindocr/data/table_pubtab_dataset.py, mindocr/data/transforms/table_transform.py, mindocr/data/transforms/transforms_factory.py, mindocr/losses/builder.py, mindocr/losses/table_master_loss.py, mindocr/metrics/builder.py, mindocr/metrics/table_metrics.py, mindocr/models/backbones/__init__.py, mindocr/models/backbones/table_master_resnet.py, mindocr/models/heads/builder.py, mindocr/models/heads/table_master_head.py, mindocr/postprocess/builder.py, mindocr/postprocess/table_postprocess.py, mindocr/utils/dict/table_master_structure_dict.txt
=> add TableMaster table recognition model

mindocr/utils/misc.py
=> fix log print with loss inf

configs/det/dbnet/db_mobilenetv3_icdar15_8p.yaml, docs/cn/tutorials/frequently_asked_questions.md, docs/en/tutorials/frequently_asked_questions.md, mindocr/data/builder.py
1. improve training performance of dbnet_mobilenetv3 by using minddata transforms on Ascend910 series
2. add distributed config file for training dbnet_mobilenetv3_icdar2015 using 8P Ascend910 series
=> improve training performance of db_mv3

configs/det/dbnet/db_r50_icdar15.yaml, configs/rec/crnn/crnn_resnet34.yaml, mindocr/data/predict_dataset.py, mindocr/models/cls_mv3.py, mindocr/models/det_dbnet.py, mindocr/models/det_psenet.py, mindocr/models/kie_layoutxlm.py, tests/ut/test_mindir_export.py, tests/ut/test_models.py, tools/export.py, tools/infer/text/config.py, tools/infer/text/postprocess.py, tools/infer/text/predict_det.py, tools/infer/text/predict_from_yaml.py, tools/infer/text/predict_rec.py, tools/infer/text/predict_ser.py
2.introduce online inference based on yaml.
=> Bug fixes for online inference and introduce online inference based on yaml

tools/infer/text/predict_from_yaml.py
Bug some bug of online inference
=> bug fix of online inference

tools/infer/text/predict_from_yaml.py
…ults.
为`predict_single_step`函数增加保存结果参数，使得在ocr推理时可以设置中间结果是否保存。
=> Added option for predict_single_step whether to save intermediate reults.

.github/workflows/python-publish.yml, MANIFEST.in, mindocr/version.py, requirements.txt, tools/infer/text/config.py, tools/infer/text/res_eval.py
1. revise whl deploy setting and version info 
2. revise requirements.txt to fix issue #470 
=> revise whl deploy setting and version info

.gitmodules
=> add mindformers as third party

mindocr/data/transforms/general_transforms.py
=> fix data bug

tools/modelarts_adapter/modelarts.py
Bugfix of modelers
修复modelarts的bug
#582 
=> Bugfix of modelarts

tests/st/test_overfit.py
=> add testcase

tools/eval.py, tools/train.py
=> add jit config level O2 for training scripts to support ms 2.3.0 version

configs/rec/abinet/abinet_resnet45_en.yaml, tools/train.py
=> abinet set context

configs/rec/abinet/abinet_resnet45_en.yaml, tools/train.py
=> abinet set context to v0.4.0

configs/rec/svtr/svtr_tiny_8p.yaml
=> fix svtr_tiny 8p loss except to v0.4.0

configs/rec/svtr/svtr_tiny_8p.yaml
=> fix svtr_tiny 8p loss except

README.md, README_CN.md, configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/rec/abinet/README.md, configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/svtr/README.md
=> add 910* test result

.github/workflows/ci.yml, mindocr/models/utils/attention_cells.py, tests/ut/test_mindir_export.py
=> change ci config

README.md
=> remove device type from version table

configs/rec/svtr/svtr_tiny.yaml, configs/rec/svtr/svtr_tiny_ch.yaml
=> set svtr config drop_overflow_update True

mindocr/models/utils/attention_cells.py
=> fix ops masked_fill

deploy/py_infer/src/data_process/preprocess/transforms/det_transforms.py
修复bug  litmit_side_len存在多个同名参数
=> fix bug litmit_side_len

deploy/py_infer/src/data_process/preprocess/transforms/det_transforms.py
=> fix bug litmit_side_len to master

deploy/cpp_infer/src/base/command_parser/command_parser.cpp, deploy/cpp_infer/src/base/config_parser/config_parser.cpp, deploy/cpp_infer/src/main.cpp, deploy/cpp_infer/src/parallel/framework/module_base.cpp, deploy/cpp_infer/src/parallel/framework/module_manager.cpp, deploy/cpp_infer/src/parallel/module/classification/cls_infer_node.cpp, deploy/cpp_infer/src/parallel/module/classification/cls_post_node.cpp, deploy/cpp_infer/src/parallel/module/classification/cls_pre_node.cpp, deploy/cpp_infer/src/parallel/module/common/collect_node.cpp, deploy/cpp_infer/src/parallel/module/detection/det_infer_node.cpp, deploy/cpp_infer/src/parallel/module/detection/det_pre_node.cpp, deploy/cpp_infer/src/parallel/module/recognition/rec_infer_node.cpp, deploy/cpp_infer/src/parallel/module/recognition/rec_pre_node.cpp, deploy/cpp_infer/src/utils/utils.cpp
fix bug about ci(check-cpplint)
=> fix check_cpplint

configs/table/README.md, configs/table/README_CN.md, mindocr/metrics/builder.py, mindocr/models/heads/table_master_head.py, mindocr/postprocess/builder.py
The inference performance of the original TableMasterHead network was not ideal, which led to the need for improvements. 
infer results:
infer results:
Eval Accuracy improvement:
77.43% -> 77.49%
Train test(part of log, singe card by graph mode):
Related Issues: [Update TableMasterHead](https://github.com/mindspore-lab/mindocr/issues/745)
=> update tablemasterhead network

configs/det/dbnet/README_CN.md
=> docs: add missed form in README_CN

configs/det/dbnet/README_CN.md
=> branch v0.4.0 pr  docs: add missed form in README_CN

examples/license_plate_detection_and_recognition/README.md, examples/license_plate_detection_and_recognition/README_CN.md
=> revise document of license plate demo

configs/layout/layoutlmv3/README.md, configs/layout/layoutlmv3/README_CN.md
=> Add 2.4.0 information to the LayoutLMv3 readme

.github/workflows/ci.yml, deploy/eval_utils/eval_rec.py, deploy/py_infer/src/data_process/postprocess/builder.py, docs/en/tutorials/frequently_asked_questions.md, docs/zh/tutorials/frequently_asked_questions.md, mindocr/models/backbones/yolov8_backbone.py, mindocr/models/heads/yolov8_head.py, tools/infer/text/predict_llm.py, tools/train.py
=> update set_context API for ms2.5 version

mindocr/models/backbones/yolov8_backbone.py, mindocr/models/heads/yolov8_head.py
=> fix set_device twice bug
