mindspore-lab/mindocr

tests/ut/test_loss.py, tests/ut/test_postprocess.py
=> add ut for build_loss and build_postprocess

deploy/mx_infer/framework/module_base.py, deploy/mx_infer/framework/module_manager.py, deploy/mx_infer/infer_pipeline.py, deploy/mx_infer/pipeline.py, deploy/mx_infer/pipeline_args.py, deploy/mx_infer/processors/__init__.py, deploy/mx_infer/processors/classification/cls_infer_process.py, deploy/mx_infer/processors/classification/cls_pre_process.py, deploy/mx_infer/processors/common/collect_process.py, deploy/mx_infer/processors/common/decode_process.py, deploy/mx_infer/processors/common/handout_process.py, deploy/mx_infer/processors/detection/det_infer_process.py, deploy/mx_infer/processors/detection/det_post_process.py, deploy/mx_infer/processors/detection/det_pre_process.py, deploy/mx_infer/processors/recognition/rec_infer_process.py, deploy/mx_infer/processors/recognition/rec_post_process.py, deploy/mx_infer/processors/recognition/rec_pre_process.py, deploy/mx_infer/utils/safe_utils.py
fix some import path for inference
There are other folders under deploy path, but none of them are Python packages.
So mx_ Infer should be used as the root directory for inference packages.
=> fix some import path for inference

configs/det/dbnet/db_r50_icdar15.yaml, mindocr/data/transforms/general_transforms.py, mindocr/postprocess/det_postprocess.py
Passing images to the `RandomColorAdjust` MindSpore's transform as `np.ndarray` causes training freeze when the `data_sink_mode` is set to `True`. This fix converts images to the `PIL` format first and converts them back to `np.ndarray` after color adjustment.
=> fix `data_sink_mode` freeze, adjust DBNet augmentation pipeline

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md
=> update model readmes for mindir download urls

configs/rec/crnn/crnn_icdar15.yaml, mindocr/utils/loss_scaler.py, mindocr/utils/train_step_wrapper.py, tests/st/test_train_eval_dummy.py
=> Del gradient accumulation for potential loss unconvergence in dbnet

configs/det/dbnet/db_r50_icdar15.yaml, configs/det/dbnet/db_r50_synthtext.yaml, configs/rec/crnn/crnn_icdar15.yaml, configs/rec/crnn/crnn_resnet34.yaml, configs/rec/crnn/crnn_vgg7.yaml, mindocr/utils/callbacks.py, mindocr/utils/logger.py, tests/ut/test_logger.py, tools/train.py
=> add logger module

mindocr/models/heads/det_db_head.py, mindocr/postprocess/det_postprocess.py
=> DBNet output changed  in inference mode for faster speed - only binary map is output

README.md, README_CN.md, docs/cn/datasets/icdar2015_CN.md, docs/cn/datasets/mlt2017_CN.md, docs/en/datasets/icdar2015.md, docs/en/datasets/mlt2017.md, mindocr/data/transforms/iaa_augment.py, tools/convert_datasets.sh, tools/dataset_converters/README.md, tools/dataset_converters/README_CN.md, tools/dataset_converters/mlt2017.py, tools/dataset_converters/totaltext.py
1. README.md and README_CN.md, increases the `Dataset` section, introducing the method to download and convert datasets;
2. fix some link errors:
3. fix convert_datasets.sh missing `fi` problem;
4. fix IaaAugment bug;
5. fix tools/dataset_converters/totaltext.py bug
=> Datasets Conversion Support and Fixing Bugs

configs/det/dbnet/db_r50_icdar15.yaml, mindocr/models/backbones/builder.py, mindocr/models/backbones/mindcv_models/_feature.py, mindocr/models/backbones/mindcv_models/mobilenet_v3.py, mindocr/models/backbones/mindcv_models/model_factory.py, mindocr/models/backbones/mindcv_models/resnet.py, mindocr/models/backbones/mindcv_wrapper.py
Support intermediate feature extractions using backbones from mindcv (resnet and mobilenetv3). 
It is migrated fro this [PR](https://github.com/mindspore-lab/mindcv/pull/605)
You need to add `features_only` and `out_indices` in backbone configuration, to extract the feature pyramid. The examples is shown in the modified `db_r50_icdar15.yaml`
=> support feature extraction of mindcv backbone: resnet and mobiletnet v3

mindocr/models/backbones/mindcv_models/utils.py
…om mindcv when the feature encoder is unfold to extract intermediate features
Some vision backbone in MindCV is wrapped by nn.SequentialCell, so we have to unfold it to extract intermediate features. As a result, the pretrained weights in MindCV can not be loaded to the unfolded encoder. 
This PR fix this problem by finding the most matching layer name between a fail-to-load net param and checkpoint params.
=> add automapping function in load_pretrain to fix load weight erorr from mindcv when the feature encoder is unfolded to extract intermediate features

deploy/demo/mindocr_lite/README.md, deploy/demo/mindocr_lite/README_CN.md, deploy/demo/mindocr_lite/src/processors/detection/det_post_process.py
1.补充一下文本检测和识别中，评估精度时gt和pred的文本格式
2.修复一些格式问题
=> add illustration for annotation format for inference

mindocr/models/backbones/rec_resnet.py, mindocr/models/necks/rnn.py, mindocr/utils/callbacks.py, mindocr/utils/model_wrapper.py, tools/train.py
=> fix bugs in mixed precision training

README.md, README_CN.md, docs/cn/datasets/td500_CN.md, docs/en/datasets/td500.md, tools/convert_datasets.sh, tools/dataset_converters/convert.py, tools/dataset_converters/td500.py
add td500 dataset convert and readme
=> add td500 dataset convert

mindocr/models/backbones/builder.py, mindocr/models/builder.py, mindocr/models/utils.py, tools/train.py
=> Add pretrained ckpt loading (via local path or url) to support finetuning

README.md, README_CN.md, docs/cn/predict_ckpt_cn.md, docs/en/predict_ckpt.md, tools/predict/text/utils_predict.py
Updata docs for predict_system
=> update docs for predict_system

README.md, README_CN.md, configs/det/dbnet/db_r18_icdar15.yaml, configs/det/dbnet/db_r50_icdar15.yaml, configs/det/dbnet/db_r50_synthtext.yaml, configs/rec/crnn/crnn_icdar15.yaml, configs/rec/crnn/crnn_resnet34.yaml, configs/rec/crnn/crnn_vgg7.yaml, configs/rec/crnn_seq2seq/crnn_seq2seq_resnet34.yaml, docs/cn/predict_ckpt_cn.md, mindocr/data/builder.py, mindocr/data/transforms/rec_transforms.py, mindocr/losses/builder.py, mindocr/losses/rec_loss.py, mindocr/models/README.md, mindocr/models/base_model.py, mindocr/models/heads/builder.py, mindocr/models/heads/rec_attn_head.py, mindocr/postprocess/rec_postprocess.py, mindocr/utils/callbacks.py, mindocr/utils/model_wrapper.py, tools/eval.py, tools/train.py
=> Add Rec Seq2seq components and configure file, change all config files due to interface change

tools/modelarts_adapter/modelarts.py
Pip cannot be upgraded successfully on modelart due to networking issue
=> use proxy when upgrading pip on modelart

mindocr/utils/callbacks.py, mindocr/utils/model_wrapper.py
=> Change the default value of the label indices from [1] to [1:]

tests/ut/test_mindir_export.py, tools/export.py
Two ways to load ckpt and export mindir file:
(1) If do not specify `local_ckpt_path`, download online ckpt from url in default_cfg.
(2) If specify `local_ckpt_path` and `model_name`, load local ckpt for exporting a specific model.
=> fix export.py to support loading either local or online ckpt

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/dbnet/db++_r50_icdar15.yaml, mindocr/models/det_dbnet.py, mindocr/models/necks/asf.py, mindocr/models/necks/fpn.py
=> add DBNet++ support

README.md, README_CN.md, docs/cn/datasets/ctw1500_CN.md, docs/en/datasets/ctw1500.md, tools/convert_datasets.sh, tools/dataset_converters/convert.py, tools/dataset_converters/ctw1500.py
=> add ctw1500 dataset convert

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/dbnet/db_r50_td500.yaml
add dbnet yaml for synthtext dataset and td500 dataset
related issue #222 
=> add dbnet yaml for synthtext dataset and td500 dataset

mindocr/utils/callbacks.py, tools/train.py
Average loss across devices to see better training stats.
=> loss averaging across multiple devices

mindocr/data/builder.py, mindocr/data/transforms/rec_transforms.py, mindocr/losses/builder.py, mindocr/losses/rec_loss.py, mindocr/models/backbones/builder.py, mindocr/models/utils.py, mindocr/optim/adan.py, mindocr/optim/param_grouping.py, mindocr/postprocess/rec_postprocess.py, mindocr/utils/callbacks.py, mindocr/utils/logger.py, requirements.txt, tests/ut/test_logger.py, tools/train.py
Improve log info.
Archive original yaml config used in training to better ensure reproduction.
Fix Adan optimizer (sync mindcv)
=> Improve log, save origin yaml, and fix adan

mindocr/utils/callbacks.py
Somehow `cur_lr` will be `[0.111]` instead of `0.111` in some cases. Which will raise the formatting error in the logging message from PR #272. This is a fix
=> fix the formatting error

configs/rec/crnn/crnn_icdar15.yaml, mindocr/data/constants.py, mindocr/utils/callbacks.py, mindocr/utils/checkpoint.py, tools/train.py
=> Add checkpoint manager to save latest or top k checkpoints in history

mindocr/data/transforms/general_transforms.py
=> fix errors in validate polygons (temp solution)

tools/modelarts_adapter/modelarts.py, tools/train.py
- Support relative path of config file in ModelArt (e.g., config=configs/rec/crnn/crnn_resnet34.yaml)
- Remove the hard code of device id from #279 
=> Support relative path of config file in ModelArt and fix bug

mindocr/data/builder.py
=> fix bug when set label_file: null

mindocr/models/heads/rec_attn_head.py, mindocr/models/utils/rnn_cells.py
=> handle the softmax error form ms_2.0alpha and clean warning

configs/rec/crnn/crnn_resnet34_ch.yaml, docs/cn/datasets/chinese_text_recognition_CN.md
There is an `inf` loss when converting predictions to fp32, as a quick fix, set pred_cast_fp32 to False.
Also updated lr to align the configuration of the uploaded model.
=> Update CRNN-CH config and fix readme format bug

deploy/py_infer/src/configs/det/ppocr/ch_PP-OCRv2_det_cml.yaml, deploy/py_infer/src/configs/det/ppocr/ch_det_mv3_db_v2.0.yaml, deploy/py_infer/src/configs/rec/ppocr/arabic_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/ch_PP-OCRv2_rec_distillation.yaml, deploy/py_infer/src/configs/rec/ppocr/chinese_cht_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/cyrillic_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/devanagari_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/en_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/japan_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/ka_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/korean_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/latin_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/rec_chinese_lite_train_v2.0.yaml, deploy/py_infer/src/configs/rec/ppocr/rec_en_number_lite_train.yaml, deploy/py_infer/src/configs/rec/ppocr/ta_PP-OCRv3_rec.yaml, deploy/py_infer/src/configs/rec/ppocr/te_PP-OCRv3_rec.yaml, deploy/py_infer/src/data_process/postprocess/postprocess_mapping.py, deploy/py_infer/src/data_process/postprocess/rec_postprocess.py, deploy/py_infer/src/data_process/preprocess/preprocess_mapping.py, deploy/py_infer/src/utils/adapted/paddleocr_models.py
1. 适配ppocr系列模型，增加ppocr系列模型的推理配置文件，以及进行模型注册。
=> Add ppocr series models

configs/det/dbnet/db++_r50_icdar15.yaml, configs/det/dbnet/db_r18_icdar15.yaml, configs/det/dbnet/db_r50_icdar15.yaml, mindocr/data/transforms/det_transforms.py, mindocr/data/transforms/general_transforms.py, mindocr/data/transforms/rec_transforms.py, mindocr/data/transforms/transforms_factory.py
=> Add a unified resize operation for detection and a resize op for recognition inference

configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/rare/README.md, configs/rec/rare/README_CN.md, configs/rec/svtr/README.md, configs/rec/svtr/README_CN.md, configs/rec/svtr/svtr_tiny.yaml, mindocr/data/transforms/rec_transforms.py, mindocr/data/transforms/svtr_transform.py, mindocr/data/transforms/transforms_factory.py, mindocr/models/__init__.py, mindocr/models/backbones/__init__.py, mindocr/models/backbones/rec_resnet.py, mindocr/models/backbones/rec_svtr.py, mindocr/models/backbones/rec_vgg.py, mindocr/models/base_model.py, mindocr/models/necks/builder.py, mindocr/models/necks/img2seq.py, mindocr/models/rec_svtr.py, mindocr/models/transforms/__init__.py, mindocr/models/transforms/builder.py, mindocr/models/transforms/stn.py, mindocr/models/transforms/tps_spatial_transformer.py, mindocr/optim/param_grouping.py, tools/benchmarking/multi_dataset_eval.py, tools/eval.py
=> Add SVTR Tiny model

mindocr/models/backbones/mindcv_models/download.py, mindocr/models/backbones/mindcv_models/utils.py, mindocr/models/utils/load_model.py
1. Support non-strict way of loading checkpoint like Pytorch.  e.g, skip loading the parameters if the shape is not same, instead of raising exception. 
2. Refactor funcs in mindcv_models.utils.py, such that it is reusable in utility `load_model` in `load_model.py`.
=> support non-strict checkpoint loading

mindocr/models/base_model.py
**Problem:**
ms.export interface loads the variable names in network to build the mindir files. Therefore, the change (`x` -> `tout`) of the input variable name of backbone will cause bugs while using convert_lite tool to convert mindir files for lite inference.
**Solution:**
Keep the input variable name of backbone as `x` to ensure backward compatibility. The models trained before can be converted to mindir files without additional modification on variable name mapping while using convert_lite tool.
=> modify transform op output variable name to avoid mindir conversion bug

deploy/py_infer/src/infer/infer_det.py
When the detection polys is empty, they may be multiple shape formats, so they need to be unified into the same shape.
=> fix det inference bug when empty

mindocr/data/transforms/det_transforms.py, mindocr/losses/det_loss.py
Fix issue#333 and modify some codes according the comments of Rustam.
Already tested on CTW1500 dataset with shape (736, 736)
Issues: https://github.com/mindspore-lab/mindocr/issues/333
PR: https://github.com/mindspore-lab/mindocr/pull/290
=> PSEDiceLoss support any input shape (fix issue#333)

mindocr/data/builder.py, mindocr/data/transforms/det_transforms.py, mindocr/data/transforms/general_transforms.py, mindocr/data/transforms/rec_transforms.py, mindocr/postprocess/det_base_postprocess.py, mindocr/postprocess/det_db_postprocess.py, mindocr/postprocess/det_east_postprocess.py, mindocr/utils/evaluator.py
- Fixed bug that caused evaluation crash if no postprocessing is set.
- Fixed `DetBasePostprocess` class import from outside and refactored it.
- Moved training condition check to initialization in `RandomScale` as this condition needs to be checked once only.
- Reverted linting in `mindocr/data/builder.py` to avoid complicated merge conflicts with the new pipeline (#300).
- Set `shape_list` as numpy array throughout the project.
- Removed polygons clipping in `DBPostprocess` to keep all the clippings in one place (`DetBasePostprocess`).
=> Small fixes to post-processing pipeline

configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/crnn/crnn_resnet34_ch.yaml, configs/rec/rare/README.md, configs/rec/rare/README_CN.md, configs/rec/rare/rare_resnet34.yaml, configs/rec/rare/rare_resnet34_ch.yaml, configs/rec/svtr/README.md, configs/rec/svtr/README_CN.md, configs/rec/svtr/svtr_tiny.yaml, configs/rec/svtr/svtr_tiny_ch.yaml, mindocr/data/rec_lmdb_dataset.py, mindocr/data/transforms/rec_transforms.py, mindocr/losses/rec_loss.py, mindocr/models/backbones/rec_svtr.py, mindocr/models/rec_crnn.py, mindocr/models/rec_rare.py, mindocr/models/rec_svtr.py, mindocr/models/transforms/tps_spatial_transformer.py, mindocr/postprocess/rec_postprocess.py, requirements/modelarts.txt, tools/export.py
1. CRNN Model improvement
Scene: 59.71% -> 60.45%
Web: 64.86% -> 65.95%
Document: 89.23% -> 97.68%
2. Seq2Seq Model Improvement
Scene: 55.39% -> 62.15%
Web: 61.90% -> 67.05%
Document: 97.05% -> 97.60%
FPS: 1493 -> 2160
2. Add SVTR Model
Scene: 65.93%
Web: 69.64%
Document: 98.01%
4. Chinese benchmark model supported vertical image recognition
5. Support filtering the samples when the label length is larger than the `max_label_len` during training
6. Add AMP convert during model export
(Is this PR part of a group of changes? Link the other …
=> Add SVTR Chinese.benchmark model and Update CRNN benchmark model, and others

mindocr/data/transforms/det_transforms.py, mindocr/postprocess/det_db_postprocess.py, mindocr/postprocess/det_pse_postprocess.py
…t Poly type in PSE postprocess
fix bugs when inference using DBPostprocess: 
handle with shape (N, 1, H, W), (N, 3, H, W), (N, H, W)
fix bugs when inference using ScalePadImage:
resize_h and resize_w may be larger than tar_h, tar_w
make PSE postprocess type support poly type 
=> fix bugs when inference using DBPostprocess and ScalePadImage

mindocr/models/builder.py, tests/ut/test_mindir_export.py, tools/benchmarking/multi_dataset_eval.py, tools/eval.py, tools/export.py, tools/infer/text/config.py, tools/infer/text/predict_det.py, tools/infer/text/predict_rec.py, tools/train.py
- set the network's amp_level inside `build_model()` instead of outside 
- remove export.py input `args.amp_level`, load the `system.amp_level_infer` from input yaml (if export using yaml)
=> refactor param amp_level usage when build_model, remove export.py input args.amp_level

deploy/py_infer/src/data_process/preprocess/transforms/rec_transforms.py
修复SVTR推理时是否padding的问题，不padding时也是静态的，删除告警
=> fix svtr infer

.flake8, mindocr/metrics/builder.py, tools/dataset_converters/convert.py
add rule in .flake8 to avoid checking the module imported but unused in convert.py
=> fix bug in convert.py caused by flake8 check

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/east/README.md, configs/det/east/README_CN.md, configs/det/psenet/README.md, configs/det/psenet/README_CN.md, deploy/py_infer/src/infer_args.py, deploy/py_infer/src/utils/adapted/__init__.py, docs/cn/inference/inference_tutorial_cn.md, docs/en/inference/inference_tutorial_en.md
简化接口参数，和训练端对齐
det_model_name/det_config_path  -> det_model_name_or_config
cls_model_name/cls_config_path     -> cls_model_name_or_config
rec_model_name/rec_config_path   ->  rec_model_name_or_config
对于推理接口参数det_model_name和det_config_path，前者传入模型名，后者传入模型yaml路径，两者是关联对应的
用户在使用时二选一，用以确定预后处理参数，导致易用性低
现在合二为一改成一个参数det_model_name_or_config，和训练侧对齐，同时支持传入模型名和yaml路径
=> fix infer args

README.md, README_CN.md, docs/cn/tutorials/training_detection_custom_dataset.md, docs/en/tutorials/training_detection_custom_dataset.md, docs/en/tutorials/training_recognition_custom_dataset.md
Tutorials on how to train text detection models on custom datasets.
=> detection tutorials [WIP]

deploy/models_utils/onnx_optim/insert_pse_postprocess.py, deploy/py_infer/src/configs/det/ppocr/det_r50_vd_pse.yaml, deploy/py_infer/src/data_process/postprocess/det_postprocess.py, docs/cn/inference/models_list_thirdparty.md, docs/en/inference/models_list_thirdparty.md, mindocr/postprocess/det_pse_postprocess.py
Accelerate ppocr PSENet inference time and add modify onnx script
=> Accelerate ppocr PSENet and add modify onnx script

configs/cls/mobilenetv3/cls_mv3.yaml, docs/cn/tutorials/yaml_configuration.md, docs/en/tutorials/yaml_configuration.md, tools/benchmarking/multi_dataset_eval.py, tools/eval.py, tools/train.py
There are two ways to specify device id while standalone training:
- (1) export DEVICE_ID=7
- (2) set 'device_id=7' in system section of yaml config file
We take (1) as the higher priority, namely, (2) is only valid when distribute=False (standalone training) and environment variable 'DEVICE_ID' is NOT set.
=> Modify device_id setting way to avoid ambiguity while setting device_id by env variable or yaml

mindocr/models/necks/rnn.py, mindocr/models/utils/rnn_cells.py
logging is not support in graph mode currently
=> fix the logging in construct part and clean content expression

mindocr/utils/callbacks.py, mindocr/utils/misc.py
When resuming training, the correct logging should be [cur_epoch/(training_epochs+start_epochs)] to avoid confusion. 
It is possible that opt.get_lr() is not a single scalar but a list of scalars. When users pass a list of dictionaries to the optimizer, for example:
```
[{  'params': group_base_params , 'lr': base_lr },   { 'params': group_small_params, 'lr': small_lr}]
```
The visualization should print each distinct lr.
1. Try to resume training when start_epoch >1
2. In mindocr/optim/param_grouping.py, create a new grouping function that returns a list of dictionaries containing different lrs, for example:
```
def grouping_params(params, filter_name, learning_rate):
base_params, …
```
=> callbacks revision: allow group lr and correct the logging for resuming training

mindocr/utils/visualize.py
Remove axes and white margins around images in the inference mode.
=> remove axes and white margins around images in the inference mode

deploy/py_infer/src/data_process/postprocess/det_fce_postprocess.py, deploy/py_infer/src/data_process/postprocess/det_sast_postprocess.py, deploy/py_infer/src/utils/visual_utils.py, tests/ut/test_infer_postprocess.py
1. 训练侧的box_type, rescale_fields参数顺序修改了，推理侧没有被同步修改
2. 绘图时字体文件没有使用到输入值
=> fix infer postprocess init

configs/rec/rare/README.md, configs/rec/rare/README_CN.md
=> Add RARE MindIR

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md
Multi devices fps = Single device fps * device count
=> update readme fps

mindocr/utils/callbacks.py, mindocr/utils/misc.py
Recent change on callback.py cause `RuntimeError: Couldn't get correct hccl hcom with group hccl_world_group` in MindSpore 1.10 in OpenI. Seems ops.ReduceSum must be compiled first. This is a fix.
Meanwhile this change give a better loss value report once the loss output is fp16.
=> Fix error during loss reduce in callback

mindocr/data/transforms/general_transforms.py
During training, the RandomScale transform randomly scaled the images in the datasets; however, in some datasets, there are mixtures of small and big images, which, when scaled randomly, may lead to extremely small or extremely large images.
Therefore, this PR implements the logic of taking the minimum and maximum side lengths (`side_limits`) as arguments and then using them to calculate the scaling factor, so the randomly scaled images always stay within the specified reasonable limits.
(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use …
=> Add size limits to RandomScale transform

mindocr/models/necks/fpn.py
Change this API to accept dynamic shape input
Already tested and model results are the same.
=> Replace deprecated ResizeBilinear for EAST

tools/train.py
Sometimes the saving config takes very long time (especially for large dataset and thus the optimizer.lr is very long) and may even stuck. The log saying the training is start but actually it is not. So suggested to move the config saving before logging of "training start"
=> Move save config before training start log

README.md, README_CN.md, configs/rec/robustscanner/README.md, configs/rec/robustscanner/README_CN.md, docs/cn/index.md, docs/cn/mkdocs/modelzoo_training.md, docs/en/index.md, docs/en/mkdocs/modelzoo_training.md
=> update readme for supporting RobustScanner

mindocr/data/builder.py
Print number of all samples in distributed mode, not only the number on the main device.
=> print number of all samples in distributed mode

mindocr/models/heads/rec_visionlan_head.py, mindocr/postprocess/rec_postprocess.py, tests/ut/test_models.py
Because of #444  , the BaseModel.construct() has been changed, I also need to change visionlan head to make it compatible.
=> fix visionlan head for multiple inputs

tools/export.py, tools/infer/text/predict_det.py, tools/infer/text/predict_rec.py, tools/infer/text/predict_system.py
Some datasets have `category.name.jpg` file naming. Current prediction pipeline splits names by the first dot and generates images with `category.jpg` names, thus overwriting them. This PR solves this problem and keeps the visualized image names as `category.name.jpg`.
=> fix output file names for prediction pipeline

mindocr/data/transforms/det_transforms.py, mindocr/data/transforms/general_transforms.py
PR #460 added support of samples with no text instances (as in test sets of some datasets). This PR fixes some remaining bugs in the data transformation pipeline: it checks whether text instances are present in a sample before applying operations that don't support empty arrays (e.g. `cv2.transform()`).
=> fix empty polygons processing

configs/rec/master/README.md, configs/rec/master/README_CN.md, configs/rec/master/master_resnet31.yaml, docs/cn/mkdocs/modelzoo_training.md, docs/en/mkdocs/modelzoo_training.md, mindocr/models/heads/rec_master_decoder.py, mindocr/models/necks/master_encoder.py, mindocr/models/rec_master.py, mindocr/models/utils/attention_cells.py
- Fixed the scaling value bug in attention cell, and also make the network runnable in pynative mode. Refer to the issue https://gitee.com/mindspore/mindspore/issues/I7M0XX#note_19754663. This modification make the network slightly more accurate.
- Use `inf` value to replace the large value in attention's mask, thus we can remove the type casting of fp32 during the attention calculation safely, it brings us a roughly 5% speed improvement.
- Clean all warning of the dropout in Master model in MindSpore 2.0
(Is this PR part of a group of …
=> Update Master Model

mindocr/models/backbones/mindcv_models/utils.py, tests/ut/test_mindir_export.py
When loading a pretrained model using `build_model(model_name, pretrained=True)`, sometimes due to internet connection error, the downloaded ckpt file was empty.  If using the old `load_checkpoint`, it will only give warnings that can be easily ignored among lots of other warnings.  
I think  `load_checkpoint` should not allow loading empty ckpt files. When the loading failed, the program should be stopped.
In addition, `visionlan_resnet45` is added to `test_mindir_export.py` and has passed the test.
=> load_checkpoint does not allow empty ckpt file

configs/rec/visionlan/visionlan_resnet45_LA.yaml, configs/rec/visionlan/visionlan_resnet45_LF_1.yaml, configs/rec/visionlan/visionlan_resnet45_LF_2.yaml, mindocr/data/transforms/svtr_transform.py
After `data/transforms/svtr_transform.py` has been revised to ensure randomness during training, visionlan training gets difficulty in loss convergence. I checked and found that `CVRescale` is the reason. 
After removing `CVRescale` from `SVTRRecAug` by setting `deterioration_factor` to `None`, the visionlan training gets fast convergence. This revision leads to a model with `90.86%` (previously it was `90.60%`) on ten benchmarks. I'm not ready to update the checkpoint files until I have tested the new data pipeline with the augmentation revision.
=> visionlan augmentation revision: remove CVRescale

configs/rec/visionlan/visionlan_resnet45_LA.yaml, configs/rec/visionlan/visionlan_resnet45_LF_1.yaml, configs/rec/visionlan/visionlan_resnet45_LF_2.yaml
Remove `CVRescale` from the augmentation list by setting `SVTRDeterioration.factor` to `None`. This augmentation is now aligned with the augmentation in the current main branch.
=> visionlan aug edits: remove CVRescale

mindocr/losses/det_loss.py
This PR fixes a bug in DBLoss that caused execution to crash on GPU and CPU when calculating loss on images with no text instances in them.
Fix for Issue #536.
=> DBLoss bug fix

deploy/py_infer/src/data_process/preprocess/adapted_preprocess.py, deploy/py_infer/src/data_process/preprocess/builder.py, deploy/py_infer/src/data_process/utils/cv_utils.py, deploy/py_infer/src/data_process/utils/gear_utils.py, deploy/py_infer/src/infer/infer_base.py, deploy/py_infer/src/infer/infer_cls.py, deploy/py_infer/src/infer/infer_det.py, deploy/py_infer/src/infer/infer_rec.py, deploy/py_infer/src/infer_args.py, tests/ut/test_infer_datasets.py
支持自研模型的动态Shape推理
**1. 实现逻辑：**
如果是动态shape模型，则优先加载训练侧的数据预处理模块
如果是静态shape/分档模型，则优先加载推理侧适配的数据预处理
**2. 增加了cls_batch_num和rec_batch_num参数**
和ppocr对齐，默认值取6，当模型的batch size是动态时，就从该参数中取值
=> add dynamic shape support for infer

configs/det/dbnet/db++_r50_icdar15.yaml, configs/det/dbnet/db_mobilenetv3_icdar15.yaml, configs/det/dbnet/db_r18_ctw1500.yaml, configs/det/dbnet/db_r18_icdar15.yaml, configs/det/dbnet/db_r18_mlt2017.yaml, configs/det/dbnet/db_r18_synthtext.yaml, configs/det/dbnet/db_r18_td500.yaml, configs/det/dbnet/db_r18_totaltext.yaml, configs/det/dbnet/db_r50_ctw1500.yaml, configs/det/dbnet/db_r50_icdar15.yaml, configs/det/dbnet/db_r50_mlt2017.yaml, configs/det/dbnet/db_r50_synthtext.yaml, configs/det/dbnet/db_r50_td500.yaml, configs/det/dbnet/db_r50_totaltext.yaml, configs/det/east/east_mobilenetv3_icdar15.yaml, configs/det/east/east_r50_icdar15.yaml, configs/det/fcenet/fce_icdar15.yaml, configs/det/psenet/pse_mv3_icdar15.yaml, configs/det/psenet/pse_r152_ctw1500.yaml, configs/det/psenet/pse_r152_icdar15.yaml, configs/det/psenet/pse_r50_icdar15.yaml, mindocr/data/det_dataset.py
MindSpore's `Decode` can't automatically rotate images based on the EXIF orientation information. Therefore, this PR replaces `Decode` with `OpenCV` for image reading in the detection task.
On the left is our original data pipeline output (uses `OpenCV`) and on the right is the new data pipeline (uses `Decode`):
=> remove Decode to read images in correct orientation

mindocr/data/rec_lmdb_dataset.py
=> fix the bug that the zero-text instance still in training when using custom dictionary

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/dbnet/db_r18_mlt2017.yaml, configs/det/dbnet/db_r18_td500.yaml, configs/det/dbnet/db_r18_totaltext.yaml, configs/det/dbnet/db_r50_mlt2017.yaml, configs/det/dbnet/db_r50_td500.yaml, configs/det/dbnet/db_r50_totaltext.yaml, mindocr/metrics/det_metrics.py, requirements.txt
This PR introduces several improvements to the polygons processing of the detection branch, namely:
1. Removes `poly.is_simple` condition from `det_metrics.py` as [the simplicity test is meaningful only for LineStrings and LinearRings](https://shapely.readthedocs.io/en/1.8.5/manual.html#object.is_simple) and doesn't work with polygons. `is_valid` condition is sufficient to check a polygon for self-intersections.
2. Specifies the exact version of `shapely` required as other versions were not tested.
3. Adds `ignore_orientation: True` for datasets whose ground truth labels do not match EXIF orientation (MLT2017, TD500, TotalText).
=> fix polygons processing

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/east/README.md, configs/det/east/README_CN.md, configs/det/fcenet/README.md, configs/det/fcenet/README_CN.md, configs/det/psenet/README.md, configs/det/psenet/README_CN.md, configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/master/README.md, configs/rec/master/README_CN.md, configs/rec/rare/README.md, configs/rec/rare/README_CN.md, configs/rec/svtr/README.md, configs/rec/svtr/README_CN.md, configs/rec/visionlan/README.md, configs/rec/visionlan/README_CN.md, deploy/py_infer/src/configs/det/mmocr/fcenet_resnet50_fpn_1500e_icdar2015.yaml, deploy/py_infer/src/data_process/postprocess/builder.py, deploy/py_infer/src/data_process/postprocess/det_east_postprocess.py, docs/cn/inference/convert_tutorial.md, docs/cn/inference/inference_quickstart.md, docs/cn/inference/inference_thirdparty_quickstart.md, docs/en/inference/convert_tutorial.md, docs/en/inference/inference_quickstart.md, docs/en/inference/inference_thirdparty_quickstart.md, mindocr/postprocess/det_fce_postprocess.py
1. 增加FCENet自研模型的推理，（将 https://github.com/mindspore-lab/mindocr/pull/543 同步过来合入）；
2. 由于一些模型的后处理，自研模型与第三方模型冲突，故而设置from_ppocr、from_mmocr字段在yaml中标记，在builder时区分加载，目前FCENet和EAST涉及该情况；
3. 修复一些文档的描述：
（1）自研模型的converter_lite去掉config参数，一般情况无需配置（第三方模型暂无法去掉，待全面支持动态shape后可去掉）；
（2）converter_lite的NoFusion和device参数已废弃，统一改为optimize；
（3）PSENet的shape之前描述错误，进行修复。
=> optimize inference loading and add fcenet

.github/workflows/ci.yml, requirements/docs.txt
- `mkdocs-static-i18n` has [breaking updates](https://github.com/ultrabug/mkdocs-static-i18n#upgrading-from-0x-versions) recently, from version 0.56 to 1.0.0. I tried to adapt to version 1.0.0 but failed, let's keep it version 0.56.
- Update mindspore version to 2.1 for CI.
=> update mindspore and mkdocs version for CI

mindocr/data/transforms/det_transforms.py
This experimental pull request introduces a new implementation of the `_draw_border()` method of the `BorderMap` transform in the training pipeline. 
The DBNet model uses threshold maps (aka border maps) in the training process to predict text instances borders. The `_draw_border()` method of `BorderMap` generates these borders for each text polygon in the image by computing the distance from each polygon edge to each pixel in the image.
Therefore, the original implementation of the `_draw_border()` method is particularly slow when a dataset contains large number of edges in the ground truth polygons. The new implementation in this PR utilizes OpenCV's `distanceTransform()` function to …
=> add new bordermap

mindocr/losses/rec_loss.py
The ctcloss op not surpport float16 on 910B.
In fact, the 910A is also cast to float32 on device.
=> adapt 910B, modify the ctcloss to float32

configs/det/dbnet/db_r18_ctw1500.yaml, configs/det/dbnet/db_r18_mlt2017.yaml, configs/det/dbnet/db_r18_td500.yaml, configs/det/dbnet/db_r18_totaltext.yaml, configs/det/dbnet/db_r50_ctw1500.yaml, configs/det/dbnet/db_r50_mlt2017.yaml, configs/det/dbnet/db_r50_td500.yaml, configs/det/dbnet/db_r50_totaltext.yaml
Set `model.backbone.pretrained` to False if `model.pretrained` has been set to avoid loading backbone pretrained weights redundantly.
=> disable loading backbone weights redundantly

deploy/py_infer/src/infer_args.py, deploy/py_infer/src/parallel/framework/module_base.py
当各node监听的queue为空，不加等待的限制，持续频繁访问队列是否非空，导致大量cpu资源空转：
- 空转时，总cpu开销约为1100%（若起了11个node进程，每个node占用100%cpu开销）
- `src/parallel/framework/module_base.py: 52`，`empty()`占比91.9%，并随queue为空的时间增加，占比进一步拉大
修改后
- 空转时，总cpu开销小于5%，当`node_fetch_interval`为0.001时，即每1ms询问一次
- 满转时，即图片持续喂入时，端到端性能劣化约3%，当`node_fetch_interval`为0.001时。该劣化可以设置`node_fetch_interval`为0恢复。
=> Fix high cpu consumption when queue is empty

configs/det/dbnet/db_r50_icdar15.yaml, configs/rec/crnn/crnn_resnet34.yaml, tools/infer/text/predict_from_yaml.py
为yaml config自定义推理增加**system**模式（det+crop+rec），完成串联ocr推理。
1. 新增`task_mode`参数以指定任务类型，`image_dir`参数在当模式为system时，可指定数据集位置
2. 修改`config`参数为`det_config`和`rec_config`参数，用以区分不同任务的yaml文件
=> Add system mode to predict_from_yaml.py

configs/rec/svtr/README_CN.md, configs/rec/svtr/svtr_tiny_8p.yaml
=> add SVTR-Tiny 8p training

configs/layout/yolov8/README.md, configs/layout/yolov8/README_CN.md, mindocr/data/builder.py, mindocr/data/det_dataset.py, mindocr/data/layout_dataset.py, mindocr/data/transforms/general_transforms.py
=> add minddata functions

mindocr/models/transforms/tps_spatial_transformer.py
解决已知问题：当amp_level = 'O2'时，即网络输入为FP16时，grid_sample有计算问题。因此将算子输入手动转换到FP64计算。
临时规避方案，待r2.3.0修复grid_sample计算问题后，应回退该PR。
Solve known issues: When amp_level = 'O2', that is, when the network input is FP16, grid_sample has calculation problems. Therefore, the input is manually cast to FP64.
=> Bugfix of svtr when the input is FP16 for MindSpore r2.3rc1

mindocr/models/necks/rnn.py
Bugfix for crnn when amp_level is O0.
修复crnn系列模型在amp_level为O0时的bug。
Note:
This problem is caused by ops.lstm, the bug of which occurred on MindSpore r2.3.0rc1.
This PR shall rollback of the bug of ops.lstm fixed.
=> Bugfix for crnn when amp_level is O0

mindocr/models/builder.py, mindocr/models/necks/rnn.py, mindocr/models/utils/__init__.py, mindocr/models/utils/load_model.py
为BaseModel类中的各模块设置amp_level，以便拿到属性并设置混合精度。
Set amp_level for each module in the BaseModel class to get attributes and set mixed precision.
=> Bugfix crnn

mindocr/models/backbones/rec_svtr.py, mindocr/models/transforms/stn.py, mindocr/models/transforms/tps_spatial_transformer.py, mindocr/models/utils/abinet_layers.py, tools/data_for_export_convert.py, tools/export_convert_tool.py
310p机器ocr检测和识别模型 全量export，发现可修复的bug
1. crnn_resnet34_ch convert shape匹配不上
2. 文件存在时remove报错
3. Abinet, svtr_tiny export失败解决：
(1) 有些ms版本在init里不能有tensor操作，一般是要先用numpy算好，再转成Tensor
(2)矩阵乘维度对不上，没有自动广播
=> 310p export bug fix

mindocr/data/transforms/det_fce_transforms.py, mindocr/data/transforms/det_transforms.py, mindocr/postprocess/det_fce_postprocess.py
NumPy 1.20.0 Release Notes
Using the aliases of builtin types like np.int is deprecated
numpy.int --> numpy.int_
numpy.bool --> numpy.bool_
=> fix deprecated numpy int and bool

tools/eval.py, tools/train.py
set jit_level to O2 under graph mode for better performance
=> set jit_level to O2 under graph mode

tools/eval.py, tools/train.py
This reverts commit 8ede9d33dded7a66c7819df497c815e0cb0a5696.
Revert "set jit_level to O2 under graph mode (#705)"
=> Revert "set jit_level to O2 under graph mode (#705)"

README.md, README_CN.md
=> update readme about device description

tools/eval.py, tools/train.py
=> add jit config level O2 for training scripts to support ms 2.3.0 version

deploy/py_infer/src/data_process/postprocess/det_east_postprocess.py, deploy/py_infer/src/data_process/postprocess/det_sast_postprocess.py, mindocr/postprocess/det_east_postprocess.py, mindocr/postprocess/nms_py/lanms_py.py, requirements.txt, tests/ut/test_lanms_py.py, tools/dataset_converters/ic15.py
- [✔] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ✔] Your code builds clean without any errors or warnings
- [ ✔] You are using approved terminology
- [✔ ] You have added unit tests
when I run 
```shell
pip install -r requirements.txt
```
it is failed because of  the package **lanms**, the package does not support the windows environment very well. So I read the origin paper : https://arxiv.org/pdf/1704.03155v2 ,and write the algorithm in pure Python.
and I also remain the lanms package for systems except Windows, the pure python based lanms only works in Windows.
- check the lanms is ignored when pip …
=> remove required package lanms for Windows

configs/table/README.md, configs/table/README_CN.md, mindocr/models/backbones/transformer_common/layer.py
While executing the evaluation for the vi_layoutxlm model, the following error occurred:
1. ser_vi_layoutxlm_xfund_zh.yaml 
-system.mode: 0
-model.backbone.use_float16: True
-model.head.use_float16: True
2. ser_vi_layoutxlm_xfund_zh.yaml 
-system.mode: 1
-model.backbone.use_float16: True
-model.head.use_float16: True
Or while infer the vi_layoutxlm model(by "tools/infer/text/predict_ser.py"), also occurs the following error:
It need to change numpy.float16 to mindspore.Tensor type, so it need to update finfo func.
First, use "python tools/eval.py --config configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yaml" for test:
1. ser_vi_layoutxlm_xfund_zh.yaml 
-system.mode: 0 …
=> fix bug in ops.masked_fill by updating finfo func

mindocr/utils/visualize.py, tools/infer/text/predict_ser.py
1. Update `mindocr.utils.visualize.draw_boxes` function to support `rectangle` draw_type:
The current draw_boxes function only supports drawing polygons. Adding support for drawing rectangles will enhance its versatility and make it more useful for various applications that require drawing bounding boxes in both polygon and rectangle formats.
2. Move `tools.infer.text.predict_ser.draw_ser_results `to `mindocr.utils.visualize:`
The draw_ser_results function is currently located in `tools.infer.text.predict_ser`, which may not be the most intuitive location for a utility function that deals with visualizing OCR results. Moving it to `mindocr.utils.visualize` will improve the organization of the …
=> Support rectangle in draw_boxes and relocate draw_ser_results

configs/table/README.md, tools/infer/text/README.md, tools/infer/text/README_CN.md
update doc about table model inference.
=> update doc about table model

mindocr/postprocess/det_db_postprocess.py
=> fix dbnet eval on ctw1500

configs/llm/monkey/monkey.yaml, mindocr/data/transforms/llm_transform.py, mindocr/nlp/llm/__init__.py, mindocr/nlp/llm/base_llm_model.py, mindocr/nlp/llm/builder.py, mindocr/nlp/llm/configs.py, mindocr/nlp/llm/convert_weight.py, mindocr/nlp/llm/monkey_qwen_model.py, mindocr/nlp/llm/qwen_model.py, mindocr/nlp/llm/qwen_tokenizer.py, mindocr/nlp/llm/vary_clip_model.py, mindocr/nlp/utils/flash_attention.py, mindocr/utils/conversation.py, tools/infer/text/predict_llm.py
1. Add inference codes for [Monkey](https://github.com/Yuliang-Liu/Monkey) model
2. Revise codes of OCR LLM, including extracting common functions and classes, optimizing realizations
=> add Monkey model and revise codes of OCR LLM

tools/infer/text/config.py, tools/infer/text/postprocess.py, tools/infer/text/predict_ser.py, tools/infer/text/preprocess.py
replace hardcoded paths with the ser_class_dict_path configuration parameter, enhancing flexibility and maintainability.
```
python tools/infer/text/predict_ser.py --rec_algorithm SVTR_PPOCRv3_CH --det_algorithm DB++  --image_dir configs/kie/vi_layoutxlm/example.jpg --rec_char_dict_path mindocr/utils/dict/ch_dict.txt  --ser_class_dict_path mindocr/utils/dict/class_list_xfun.txt
```
=> update config to add argument:ser_class_dict_path

mindocr/models/kie_layoutxlm.py, tools/infer/text/predict_ser.py
1. update register_model: vi_layoutxlm_ser to use pretrain ckpt
2. fix bug by inferring ser in layoutxlm_ser: 
`[ERROR] ANALYZER(2921322,ffffa6185010,python):2024-12-30-08:59:24.113.844 [mindspore/ccsrc/pipeline/jit/ps/static_analysis/evaluator.cc:713] Run] Primitive: <StandardPrimEvaluator_list_getitem> infer failed, failed info: list_getitem evaluator index should be in range[-4, 4), but got 4.`
1. infer with vi_layoutxlm: 
```python
python tools/infer/text/predict_ser.py --rec_algorithm CRNN_CH --det_algorithm DB_PPOCRv3 --image_dir configs/kie/vi_layoutxlm/example.jpg
```
2. infer with layoutxlm, the following bugs have occurred:
```python
python tools/infer/text/predict_ser.py …
```
=> use default ser ckpt in vi_layoutxlm_ser

requirements.txt
Due to the frequent installation failures caused by lanms, update lanms to the more compile-stable lanms-nova in the requirements.
Unlike lanms, lanms-nova also supports Python 3.11 compilation, thus removing the original Python version restrictions for installing lanms.
=> Update lanms to lanms-nova

mindocr/models/backbones/mindcv_models/repmlp.py, mindocr/models/heads/kie_relationextraction_head.py, mindocr/models/heads/rec_robustscanner_head.py, mindocr/models/heads/rec_sar_head.py, mindocr/models/heads/rec_visionlan_head.py
change repeat to repeat_interleave
=> change repeat to repeat_interleave

tools/dataset_converters/synthtext.py
1. Due to different lengths of sublists in the array, add dtype=object in np.array to adapt the change from Numpy 1.22.
2. Since itertools.chain does not have len() method, change iter to list.
=> fix synthText dataset convert

configs/det/dbnet/README.md, configs/det/dbnet/README_CN.md, configs/det/dbnet/README_CN_PP-OCRv3.md, configs/det/east/README.md, configs/det/east/README_CN.md, configs/det/psenet/README.md, configs/det/psenet/README_CN.md, configs/layout/yolov8/README.md, configs/layout/yolov8/README_CN.md, configs/rec/abinet/README.md, configs/rec/abinet/README_CN.md, configs/rec/crnn/README.md, configs/rec/crnn/README_CN.md, configs/rec/master/README.md, configs/rec/master/README_CN.md, configs/rec/rare/README.md, configs/rec/rare/README_CN.md, configs/rec/robustscanner/README.md, configs/rec/robustscanner/README_CN.md, configs/rec/svtr/README.md, configs/rec/svtr/README_CN.md, configs/rec/svtr/README_CN_PP-OCRv3.md, configs/rec/visionlan/README.md, configs/rec/visionlan/README_CN.md, configs/table/README.md, configs/table/README_CN.md, examples/license_plate_detection_and_recognition/README.md, examples/license_plate_detection_and_recognition/README_CN.md
=> v0.5.0 link adaption

.github/workflows/ci.yml, deploy/eval_utils/eval_rec.py, deploy/py_infer/src/data_process/postprocess/builder.py, docs/en/tutorials/frequently_asked_questions.md, docs/zh/tutorials/frequently_asked_questions.md, mindocr/models/backbones/yolov8_backbone.py, mindocr/models/heads/yolov8_head.py, tools/infer/text/predict_llm.py, tools/train.py
=> update set_context API for ms2.5 version
